server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nombre_de_la_base_de_datos
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialectct: org.hibernate.dialect.MySQL5Dialect